# Generated by Django 4.0.5 on 2022-08-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
        ('task', '0003_alter_task_labels_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, through='task.TaskLabel', to='label.label', verbose_name='labels'),
        ),
    ]
